version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /opt/docker/mysql/datadir:/var/lib/mysql
      - /opt/docker/mysql/conf.d:/etc/mysql/conf.d
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /opt/docker/redis/data:/data
  asynq:
    image: redis
    container_name: asynq
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /opt/docker/asynq/data:/data
  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    restart: always
    ports:
      - "8080:8080"
    command: ["--redis-addr=asynq:6379"]