version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/apps/nginx/html:/usr/share/nginx/html
      - /opt/apps/nginx/conf.d:/etc/nginx/conf.d
      - /opt/apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/apps/nginx/log:/var/log/nginx
    networks:
      - common-net
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /opt/apps/mysql/datadir:/var/lib/mysql
      - /opt/apps/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - common-net

networks:
  common-net:
    external: true
