version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  redis-queue:
    image: redis
    container_name: redis-queue
    ports:
      - "6380:6379"
  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    ports:
      - "8080:8080"
    command: ["--redis-addr=redis-queue:6379"]